"""Repository rules that vendor the tools of a hermetic LaTeX toolchain.

Three fetching rules — one per upstream archive — and one hub rule that binds
what they produce into a `latex_toolchain` and a registerable `toolchain`.

Each fetching rule downloads a pinned archive and writes, *next to the extracted
tree*, a small wrapper script that satisfies the corresponding `LatexInfo` CLI
contract (see `//latex:toolchain.bzl`). The wrapper resolves the tool through
its own `$0`, so it works wherever Bazel stages the repository — the action does
not have to know the layout, and nothing leaks in from the host `PATH`.

Every rule also exposes a `:files` filegroup holding the entire extracted tree.
The toolchain passes that to each action as `tools`, which is what makes the
resulting build sandboxable: the TeX engine finds its `texmf-dist` and qpdf its
shared libraries because those files are declared inputs, not ambient state.
"""

_BUILD = """\
# Generated by {rule} — do not edit.
package(default_visibility = ["//visibility:public"])

# Everything the wrapper needs at run time. Declared as action inputs by the
# toolchain, so the tools work inside the sandbox.
filegroup(
    name = "files",
    srcs = glob(["**"], exclude = ["BUILD.bazel"], allow_empty = True),
)

exports_files({wrappers})
"""

def _write_build(rctx, rule_name, wrappers):
    rctx.file(
        "BUILD.bazel",
        _BUILD.format(rule = rule_name, wrappers = repr(wrappers)),
        executable = False,
    )

def _chmod_x(rctx, *paths):
    """Restore the executable bit.

    Bazel's tar extraction keeps file modes, but its zip extraction does not
    always, so do not rely on either.
    """
    for p in paths:
        if rctx.path(p).exists:
            rctx.execute(["chmod", "+x", str(rctx.path(p))])

# --- TeX engine -------------------------------------------------------------

_PDFLATEX_WRAPPER = """\
#!/usr/bin/env bash
# Hermetic TeX engine (vendored {url}).
#
# The binary is relocatable: kpathsea locates `texmf-dist` from the engine's own
# path, so no TEXMF* variable is needed to find the distribution. It must be
# exec'd through its `pdflatex` name — the engine selects its format from
# argv[0].
set -euo pipefail
here="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

# kpathsea shells out for anything it has to generate on demand — mktextfm for a
# missing .tfm, and mf-nowin under it. Putting the vendored bin directory first
# keeps that path hermetic too; without this the engine would silently pick up
# the host's METAFONT and the output would depend on what is installed.
export PATH="$here/{bin_dir}${{PATH:+:$PATH}}"

# Those helpers write what they generate under TEXMFVAR, which points into the
# distribution and is read-only in the sandbox. Send it somewhere writable
# instead. The formats are still found: they are located relative to the engine,
# not through this variable.
export TEXMFVAR="${{TEXMFVAR:-${{HOME:-${{TMPDIR:-/tmp}}}}/.rules_latex_host/texmf-var}}"
mkdir -p "$TEXMFVAR"

exec "$here/{engine}" "$@"
"""

def _map_files(rctx, root):
    """Font map files under `root`, as paths relative to the texmf tree.

    TeX Live keeps them at `fonts/map/<driver>/<package>/<name>.map`, so the
    walk is two levels deep and needs no recursion. Uses `path.readdir` rather
    than shelling out to `find`, so discovery costs nothing from the host.
    """
    found = []
    maps = rctx.path(root + "/fonts/map")
    if not maps.exists:
        return found
    for driver in maps.readdir():
        if not driver.is_dir:
            continue
        for pkg in driver.readdir():
            if not pkg.is_dir:
                continue
            for f in pkg.readdir():
                if f.basename.endswith(".map"):
                    found.append(f.basename)
    return found

def _install_archives(rctx, bin_dir):
    """Extract content-addressed package archives into the distribution.

    TeX Live's per-package archives (the `archive/` directory of any tlnet
    snapshot) unpack relative to `texmf-dist`, which is exactly the layout the
    extracted distribution already has, so they drop straight in.

    Two housekeeping steps make the result usable, and they are the whole
    reason this is not just a download. `mktexlsr` rebuilds the `ls-R` filename
    database, without which kpathsea never sees the new files. `updmap-sys`
    registers any font map the package brought, without which the engine finds
    the metrics but cannot embed the glyphs.
    """
    if not rctx.attr.archives:
        return

    before = {m: True for m in _map_files(rctx, "texmf-dist")}
    for url, sha256 in rctx.attr.archives.items():
        rctx.download_and_extract(
            url = url,
            sha256 = sha256,
            # The archives are texmf-relative; the engine's tree is one level
            # down from the repository root.
            output = "texmf-dist",
        )

    mktexlsr = rctx.path(bin_dir + "/mktexlsr")
    if mktexlsr.exists:
        res = rctx.execute([str(mktexlsr)], timeout = rctx.attr.packages_timeout)
        if res.return_code != 0:
            fail("mktexlsr after texlive_archives failed:\n%s\n%s" % (res.stdout, res.stderr))

    added = [m for m in _map_files(rctx, "texmf-dist") if m not in before]
    if not added:
        return

    updmap = rctx.path(bin_dir + "/updmap-sys")
    if not updmap.exists:
        fail(
            "texlive_archives brought font maps (%s) but this distribution " % ", ".join(added) +
            "has no updmap-sys at %s, so they cannot be registered." % updmap,
        )
    for m in added:
        res = rctx.execute(
            [str(updmap), "--nomkmap", "--enable", "Map=" + m],
            timeout = rctx.attr.packages_timeout,
        )
        if res.return_code != 0:
            fail("updmap-sys --enable Map=%s failed:\n%s\n%s" % (m, res.stdout, res.stderr))
    res = rctx.execute([str(updmap)], timeout = rctx.attr.packages_timeout)
    if res.return_code != 0:
        fail("updmap-sys failed:\n%s\n%s" % (res.stdout, res.stderr))

def _texlive_repository_impl(rctx):
    rctx.download_and_extract(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        stripPrefix = rctx.attr.strip_prefix,
    )
    _chmod_x(rctx, rctx.attr.engine)

    bin_dir = rctx.attr.engine.rsplit("/", 1)[0] if "/" in rctx.attr.engine else "."

    # Content-addressed extras first, so a `tlmgr install` that follows sees a
    # tree that already has them and skips what is present.
    _install_archives(rctx, bin_dir)

    # Optional fetch-time package installation. Not content-addressed: it talks
    # to a CTAN mirror, so the fetched tree is only as reproducible as the
    # mirror. Prefer `archives` when a pinned fetch matters.
    if rctx.attr.packages:
        tlmgr = rctx.path(rctx.attr.engine).dirname.get_child("tlmgr")
        if not tlmgr.exists:
            fail("texlive_packages was set but this distribution has no tlmgr at %s" % tlmgr)

        # `--repository` rather than the distribution's baked-in default, which
        # is a live mirror. A live mirror serves whatever TeX Live is today;
        # this tlmgr is whatever it was when the pinned archive was built, and
        # tlmgr refuses to install across that gap ("tlmgr itself needs to be
        # updated"). The pinned snapshot is one the pinned tlmgr always agrees
        # with. Left empty, the baked-in default is used, drift and all.
        repository = (["--repository", rctx.attr.packages_repository] if rctx.attr.packages_repository else [])
        res = rctx.execute(
            [str(tlmgr)] + repository + ["install"] + rctx.attr.packages,
            timeout = rctx.attr.packages_timeout,
        )
        if res.return_code != 0:
            fail("tlmgr install %s failed:\n%s\n%s" % (
                " ".join(rctx.attr.packages),
                res.stdout,
                res.stderr,
            ))

    rctx.file(
        "pdflatex.sh",
        _PDFLATEX_WRAPPER.format(
            url = rctx.attr.url,
            engine = rctx.attr.engine,
            bin_dir = bin_dir,
        ),
        executable = True,
    )
    _write_build(rctx, "texlive_repository", ["pdflatex.sh"])

texlive_repository = repository_rule(
    implementation = _texlive_repository_impl,
    attrs = {
        "url": attr.string(mandatory = True, doc = "Archive holding a relocatable TeX distribution."),
        "sha256": attr.string(mandatory = True),
        "strip_prefix": attr.string(default = ""),
        "engine": attr.string(
            mandatory = True,
            doc = "Path of the pdflatex binary inside the stripped archive.",
        ),
        "packages": attr.string_list(
            default = [],
            doc = "TeX Live packages to add with `tlmgr install` after extraction. " +
                  "Requires network and a host perl at fetch time.",
        ),
        "packages_repository": attr.string(
            default = "",
            doc = "TeX Live repository URL `tlmgr install` fetches from. Pin a " +
                  "dated tlnet snapshot matching the distribution's vintage; " +
                  "empty means the distribution's own (live, drifting) default.",
        ),
        "archives": attr.string_dict(
            default = {},
            doc = "Content-addressed package archives to unpack into the " +
                  "distribution's texmf tree, as {url: sha256}. Unlike " +
                  "`packages`, every byte is pinned and no live mirror is " +
                  "consulted. TeX Live's own per-package archives work " +
                  "directly: any tlnet snapshot serves them under " +
                  "`archive/<package>.tar.xz`. Dependencies are not resolved; " +
                  "list what the package needs alongside it.",
        ),
        "packages_timeout": attr.int(default = 1200),
    },
    doc = "Downloads a relocatable TeX distribution and wraps its pdflatex.",
)

# --- qpdf: the pdfinfo/pdfunite contract ------------------------------------

# poppler publishes no prebuilt binaries, so the two poppler-shaped contracts
# are met by qpdf. Only the surface `combine.sh` uses is emulated: the `Pages:`
# line, and `in... out` concatenation.

_PDFINFO_WRAPPER = """\
#!/usr/bin/env bash
# `pdfinfo` contract (page count only), backed by vendored qpdf.
#   pdfinfo FILE.pdf   ->   a line "Pages:  <n>"
set -euo pipefail
here="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
pdf="${{!#}}"
pages="$(LD_LIBRARY_PATH="$here/{lib_dir}${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}" \\
  "$here/{binary}" --show-npages "$pdf")"
printf 'Pages:          %s\\n' "$pages"
"""

_PDFUNITE_WRAPPER = """\
#!/usr/bin/env bash
# `pdfunite` contract, backed by vendored qpdf.
#   pdfunite IN1.pdf IN2.pdf ... OUT.pdf
set -euo pipefail
here="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
if [[ "$#" -lt 2 ]]; then
  echo "usage: pdfunite IN.pdf... OUT.pdf" >&2
  exit 2
fi
inputs=("$@")
out="${{inputs[-1]}}"
unset 'inputs[-1]'
LD_LIBRARY_PATH="$here/{lib_dir}${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}" \\
  "$here/{binary}" --empty --pages "${{inputs[@]}}" -- "$out"
"""

def _qpdf_repository_impl(rctx):
    rctx.download_and_extract(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        stripPrefix = rctx.attr.strip_prefix,
    )
    _chmod_x(rctx, rctx.attr.binary)
    fmt = {"binary": rctx.attr.binary, "lib_dir": rctx.attr.lib_dir}
    rctx.file("pdfinfo.sh", _PDFINFO_WRAPPER.format(**fmt), executable = True)
    rctx.file("pdfunite.sh", _PDFUNITE_WRAPPER.format(**fmt), executable = True)
    _write_build(rctx, "qpdf_repository", ["pdfinfo.sh", "pdfunite.sh"])

qpdf_repository = repository_rule(
    implementation = _qpdf_repository_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "strip_prefix": attr.string(default = ""),
        "binary": attr.string(mandatory = True, doc = "qpdf path inside the stripped archive."),
        "lib_dir": attr.string(
            default = "lib",
            doc = "Directory of the shared libraries qpdf links against.",
        ),
    },
    doc = "Downloads qpdf and wraps it as the `pdfinfo` and `pdfunite` tools.",
)

# --- Ghostscript ------------------------------------------------------------

_GS_WRAPPER = """\
#!/usr/bin/env bash
# Hermetic ghostscript (vendored {url}). Used for the combined-PDF outline.
set -euo pipefail
here="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
exec "$here/{binary}" "$@"
"""

def _ghostscript_repository_impl(rctx):
    rctx.download_and_extract(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        stripPrefix = rctx.attr.strip_prefix,
    )
    _chmod_x(rctx, rctx.attr.binary)
    rctx.file(
        "gs.sh",
        _GS_WRAPPER.format(url = rctx.attr.url, binary = rctx.attr.binary),
        executable = True,
    )
    _write_build(rctx, "ghostscript_repository", ["gs.sh"])

ghostscript_repository = repository_rule(
    implementation = _ghostscript_repository_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "strip_prefix": attr.string(default = ""),
        "binary": attr.string(mandatory = True, doc = "gs path inside the stripped archive."),
    },
    doc = "Downloads a prebuilt ghostscript and wraps its binary.",
)

# --- Hub: the toolchain itself ----------------------------------------------

_HUB_BUILD = """\
# Generated by hermetic_latex_hub_repository — do not edit.
load("{toolchain_bzl}", "latex_toolchain")

# The vendored tools, bound into the provider the document rules consume.
latex_toolchain(
    name = "hermetic_latex",
    gs = "@{gs}//:gs.sh",
    pdfinfo = "@{qpdf}//:pdfinfo.sh",
    pdflatex = "@{texlive}//:pdflatex.sh",
    pdfunite = "@{qpdf}//:pdfunite.sh",
    files = [
        "@{texlive}//:files",
        "@{qpdf}//:files",
        "@{gs}//:files",
    ],
    visibility = ["//visibility:public"],
)

# Register this from your MODULE.bazel, under the name you passed to use_repo:
#
#     register_toolchains("@hermetic_latex//:all")
#
# The exec constraints matter: the pinned archives are binaries for one
# platform, so on any other host this toolchain is skipped and resolution falls
# through to the `system` toolchain that rules_latex_host registers.
toolchain(
    name = "hermetic_latex_toolchain",
    exec_compatible_with = {exec_compatible_with},
    toolchain = ":hermetic_latex",
    toolchain_type = "{toolchain_type}",
    visibility = ["//visibility:public"],
)
"""

def _hermetic_latex_hub_repository_impl(rctx):
    rctx.file(
        "BUILD.bazel",
        _HUB_BUILD.format(
            toolchain_bzl = rctx.attr.toolchain_bzl,
            toolchain_type = rctx.attr.toolchain_type,
            texlive = rctx.attr.texlive_repo,
            qpdf = rctx.attr.qpdf_repo,
            gs = rctx.attr.gs_repo,
            exec_compatible_with = repr(rctx.attr.exec_compatible_with),
        ),
        executable = False,
    )

hermetic_latex_hub_repository = repository_rule(
    implementation = _hermetic_latex_hub_repository_impl,
    attrs = {
        "texlive_repo": attr.string(mandatory = True, doc = "Apparent name of the TeX repo."),
        "qpdf_repo": attr.string(mandatory = True, doc = "Apparent name of the qpdf repo."),
        "gs_repo": attr.string(mandatory = True, doc = "Apparent name of the ghostscript repo."),
        "toolchain_bzl": attr.string(mandatory = True, doc = "Label of //latex:toolchain.bzl."),
        "toolchain_type": attr.string(mandatory = True, doc = "Label of //latex:toolchain_type."),
        "exec_compatible_with": attr.string_list(mandatory = True),
    },
    doc = "Binds the vendored tool repositories into a registerable toolchain.",
)
